### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by cngodles** [cngodles/lightspeed#1]
- [x] Display of facts while the beam moves.
- [x] Display of countdown until next planet
- [x] Transition effect when next planet is shown
- [ ] Maybe some sort of graphics in the display area
- [ ] Ability to reset to certain points
- [x] Explore CSS3 animations VS JS animation for beam.

**Comment by cngodles** [comment]
There does appear to be a CSS3 animation end callback: https://stackoverflow.com/questions/6186454/is-there-a-callback-on-completion-of-a-css3-animation
